" set the shell 
    "color setting{{{
    ""color desert 
    ""color ron      
    "color torte  
    ""color blue
    ""color darkblue
    ""color default
    ""color delek
    color desert
    ""color elflord
    ""color evening
    ""color coots_beauty_256 
    ""color graywh
    ""color koehler
    ""color morning
    ""color murphy
    ""color pablo
    ""color peachpuff
    "color shine
    ""color slate
    ""color torte
    ""color zellner
    ""color candy
    "color coots_beauty_256
    ""color solarized
    ""color vividchalk
"}}}
""****************************************
    "my sets{{{
    set t_Co=256
    set sw=4
    set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
    set termencoding=utf-8
    set encoding=utf-8
    " for the font setting
    set gfw=zhongShanXingShuBaiNianJiNianBan:h10.5:cGB23212
    set nobackup
    set ts=4
    set et
    set smarttab
    set smartindent
    set lbr
    set fo+=mB
    set sm
    set selection=inclusive
    set wildmenu
    set mousemodel=popup
    set rtp+=$GOROOT/misc/vim
    set go= " 不要图形按钮
    set guifont=Courier_New:h10:cANSI " 设置字体
    set guifont=Courier_New:h10:cANSI " 设置字体
    set ruler              " 显示标尺
    set showcmd            " 输入的命令显示出来，看的清楚些
    set whichwrap+=<,>,h,l " 允许backspace和光标键跨越行边界(不建议)
    set scrolloff=3        " 光标移动到buffer的顶部和底部时保持3行距离
    set laststatus=2       " 启动显示状态行(1),总是显示状态行(2)
    set foldenable         " 允许折叠
    "set foldmethod=syntax"  "语法折叠
    "set foldmethod=indent" 缩进折叠
    set foldmethod=marker " 标记折叠
    set nocompatible       "去掉讨厌的有关vi一致性模式，避免以前版本的一些bug和局限
    " 保存全局变量
    set viminfo+=!
    " 带有如下符号的单词不要被换行分割
    set iskeyword+=_,$,@,%,#,-
    " 显示中文帮助
    if version >= 603
    set helplang=cn
    set encoding=utf-8
    endif
""" some indent settings
    " 自动缩进
    set autoindent
    set cindent
    " Tab键的宽度
    set tabstop=4
    " 统一缩进为4
    set softtabstop=4
    set shiftwidth=4
    " 不要用空格代替制表符
    set expandtab
    " 在行和段开始处使用制表符
    set smarttab
    set smartindent " next level indent
    " 显示行号
    set nu
    " 历史记录数
    set history=1000
    "搜索逐字符高亮
    ""set hlsearch
    ""set incsearch
    "语言设置
    set langmenu=zh_CN.UTF-8
    set helplang=cn
    " 总是显示状态行
    set cmdheight=2
""}}}
    " 括号补全
    "maps{{{
    inoremap ( ()<esc>i
    inoremap [ []<esc>i
    inoremap { {}<esc>i
    inoremap " ""<esc>i
    inoremap ' ''<esc>i
    ""  for  noremap  自定义快捷键
    noremap <right> :wn<cr> 
    noremap <left> :wN<cr> 
    noremap <Up>       :N<cr> 
    noremap <Down>     :n<cr> 
    noremap <Insert>   :sort u<cr> 
    noremap <delete>   :g/^/ s//\=line('.').''<cr>
    noremap <Home>     :Tlist<cr> 
    noremap <End>      :! make<cr> 
    " set the mapleader
    let mapleader = "/"
    ""插入当前时间
    inoremap <leader>i <c-r>=strftime("%Y-%m-%d %H:%M:%S")<cr>
    ""插入文件名
    inoremap <leader>j <c-r>=expand("%:t")<cr>
    nmap <F6> :vsplit<CR>  
    nmap <F7> :split<CR>  
    nmap <F8> <c-w><c-w>
    noremap <F3>  I<esc>x 
    noremap <F4>  I#<esc> 
    "" clear the colors
    nmap <leader>n :/\$<CR>
    "" go to the placeholder, it's disgusting to use <c-j>
    "" toggle to the normal mode
    imap <leader>a <esc>:w<cr>
    nmap <leader>a :w<cr>
    "" save and quit the file
    nmap <leader>e :wqa!<CR>  
    nmap <leader>q :q<cr>
    nmap <F9> :%s/^/
    nmap <F10> :%s/$/
    ""  set paste  pattern 
    nmap <pageup> :set paste<cr>
    nmap <pagedown> :set nopaste<cr>
    "}}}

    syntax on
    ""autocmd InsertLeave * se nocul " 用浅色高亮当前行
    ""autocmd InsertEnter * se cul " 用浅色高亮当前行
    
    " 侦测文件类型
    filetype on
    " 载入文件类型插件
    filetype plugin on
    " 为特定文件类型载入相关缩进文件
    filetype indent on
    " 字符间插入的像素行数目

" vim snippets 2019-05-15"
let $BUNDLE = expand("$HOME/.vim")
let $PLUG_DIR = expand("$BUNDLE/vim-plug")

if empty(glob(expand("$PLUG_DIR/plug.vim")))
  silent !curl -fLo $PLUG_DIR/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif
source $PLUG_DIR/plug.vim
" Multiple Plug commands can be written in a single line using | separators
call plug#begin('~/.vim/plugged')

" snippets"
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
"git manager"
Plug 'airblade/vim-gitgutter'

" Initialize plugin system
call plug#end()
